import { styled, env_var_get } from "std/env"

const BOLD = 1
const FG_RED = 31
const FG_WHITE = 37
const BG_BLACK = 40

pub fun info(message: Text): Null {
    const tag = styled("info", BOLD, FG_WHITE, BG_BLACK)
    const items = ["[{tag}]: %s\n", message]

    trust $ printf "{items}" $
}

pub fun error(message: Text): Null {
    const tag = styled("error", BOLD, FG_RED, BG_BLACK)
    const items = ["[{tag}]: %s\n", message]

    trust $ printf "{items}" $
    exit 1
}
